[package]
name = "miner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
btclib = { path = "../lib" }
clap = { version = "4.5.8", features = ["derive"] }
flume = "0.11.0"
tokio = { version = "1.38.0", features = ["full"] }
